### ISSUE TITLE
simonwaldherr.de has expired certificate

### ISSUE THREAD

**Issue by Syfaro** [SimonWaldherr/fsagent#2]
Hi, 

I tried to `go get` this repo but it appears the certificate on the website has expired. 

```
https fetch failed: Get https://simonwaldherr.de/go/golibs/file?go-get=1: x509: certificate has expired or is not yet valid
```

**Comment by SimonWaldherr** [comment]
@Syfaro thanks for the info, the ssl cert was expired. I renewed the cert, it should work now.

**Comment by Syfaro** [comment]
Yep, works now!
